# Generated by Django 6.0.4 on 2026-04-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('employee', 'Employee'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
